name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  schedule:
    - cron: "0 6 * * 1-5"

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy: 
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2

      - name: install zenoh-cpp
        shell: bash
        run: |
          mkdir -p build_install && cd build_install
          cmake ../install -DCMAKE_INSTALL_PREFIX=~/local
          cmake --install .

      - name: get zenoh-c
        uses: actions/checkout@v3
        with:
          repository: eclipse-zenoh/zenoh-c
          # TODO(lucasw) this commingles it with the default checkout above of zenoh-cpp
          path: zenoh-c

      - name: install zenoh-c
        shell: bash
        run: |
          mkdir -p zenohc_build_install && cd zenohc_build_install
          cmake ../zenoh-c -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/local
          cmake --build . --target install

      - name: make standalone example with zenoh-cpp as installed package
        shell: bash
        run: |
          mkdir -p build_examples_standalone_findproj && cd build_examples_standalone_findproj
          cmake ../examples/standalone -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/local
          cmake --build . --config Release

      - name: make examples
        shell: bash
        run: |
          mkdir -p build && cd build
          cmake ..
          cmake --build . --target examples

      - name: make examples with zenoh-cpp as subbroject
        shell: bash
        run: |
          mkdir -p build_examples_subproj && cd build_examples_subproj
          cmake ../examples -DCMAKE_BUILD_TYPE=Debug
          cmake --build . --config Debug

      - name: make examples with zenoh-cpp as installed package
        shell: bash
        run: |
          mkdir -p build_examples_findproj && cd build_examples_findproj
          cmake ../examples -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/local -DZENOHCXX_SOURCE=PACKAGE
          cmake --build . --config Release

      - name: make tests
        shell: bash
        run: |
          cd build
          cmake --build . --target tests

  

      - name: run tests
        shell: bash
        run: |
          cd build
          ctest

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: zenoh-cpp-${{ matrix.os }}
          # Directory containing files to upload
          path: |
            target/release/examples
